oop homework added
shabaiev/python_skillo3 pull request #5
Opened 2020-09-20 03:07 UTC by shabaiev

2020-09-20 15:34 UTC, konflic requested changes
Hi, some improvements to be made :)

2020-09-20 15:34 UTC, konflic commented on hw_oop/ex1.py
> +        # (w * h) / 2
Remove comments

2020-09-20 15:34 UTC, konflic commented on hw_oop/ex1.py
> +    def __init__(self, w, h):
Here you have space before init, in other classes don't. Leave only one version, for codestyle to be solid.

2020-09-20 15:34 UTC, konflic commented on hw_oop/ex2.py
> +print(z.say())
This red circle means there is no new line at the end of file. Use PyCharm build in formatter to aavoid this mistakes.

2020-09-20 15:34 UTC, konflic commented on hw_oop/ex2.py
> +        # return f"Hi, I am {self.name} and I am {self.age}!"
Remove commented code in final version of your tasks

2020-09-20 15:34 UTC, konflic commented on hw_oop/ex1.py
> +    def __init__(self, w, h):
This is the complete copy of init in base class, should be removed if no changes made.

2020-09-21 14:48 UTC, konflic approved these changes

2020-10-03 18:33 UTC, closed without merging

2020-10-03 18:42 UTC, shabaiev reviewed
done

2020-10-03 18:43 UTC, shabaiev commented
oop homework